/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package eu.proasense.internal;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-3-31")
public class DerivedEvent implements org.apache.thrift.TBase<DerivedEvent, DerivedEvent._Fields>, java.io.Serializable, Cloneable, Comparable<DerivedEvent> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DerivedEvent");

  private static final org.apache.thrift.protocol.TField TIMESTAMP_FIELD_DESC = new org.apache.thrift.protocol.TField("timestamp", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField COMPONENT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("componentId", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField EVENT_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("eventName", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField EVENT_PROPERTIES_FIELD_DESC = new org.apache.thrift.protocol.TField("eventProperties", org.apache.thrift.protocol.TType.MAP, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new DerivedEventStandardSchemeFactory());
    schemes.put(TupleScheme.class, new DerivedEventTupleSchemeFactory());
  }

  public long timestamp; // required
  public String componentId; // required
  public String eventName; // required
  public Map<String,ComplexValue> eventProperties; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TIMESTAMP((short)1, "timestamp"),
    COMPONENT_ID((short)2, "componentId"),
    EVENT_NAME((short)3, "eventName"),
    EVENT_PROPERTIES((short)4, "eventProperties");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TIMESTAMP
          return TIMESTAMP;
        case 2: // COMPONENT_ID
          return COMPONENT_ID;
        case 3: // EVENT_NAME
          return EVENT_NAME;
        case 4: // EVENT_PROPERTIES
          return EVENT_PROPERTIES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TIMESTAMP_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TIMESTAMP, new org.apache.thrift.meta_data.FieldMetaData("timestamp", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.COMPONENT_ID, new org.apache.thrift.meta_data.FieldMetaData("componentId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.EVENT_NAME, new org.apache.thrift.meta_data.FieldMetaData("eventName", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.EVENT_PROPERTIES, new org.apache.thrift.meta_data.FieldMetaData("eventProperties", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ComplexValue.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DerivedEvent.class, metaDataMap);
  }

  public DerivedEvent() {
  }

  public DerivedEvent(
    long timestamp,
    String componentId,
    String eventName,
    Map<String,ComplexValue> eventProperties)
  {
    this();
    this.timestamp = timestamp;
    setTimestampIsSet(true);
    this.componentId = componentId;
    this.eventName = eventName;
    this.eventProperties = eventProperties;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DerivedEvent(DerivedEvent other) {
    __isset_bitfield = other.__isset_bitfield;
    this.timestamp = other.timestamp;
    if (other.isSetComponentId()) {
      this.componentId = other.componentId;
    }
    if (other.isSetEventName()) {
      this.eventName = other.eventName;
    }
    if (other.isSetEventProperties()) {
      Map<String,ComplexValue> __this__eventProperties = new HashMap<String,ComplexValue>(other.eventProperties.size());
      for (Map.Entry<String, ComplexValue> other_element : other.eventProperties.entrySet()) {

        String other_element_key = other_element.getKey();
        ComplexValue other_element_value = other_element.getValue();

        String __this__eventProperties_copy_key = other_element_key;

        ComplexValue __this__eventProperties_copy_value = new ComplexValue(other_element_value);

        __this__eventProperties.put(__this__eventProperties_copy_key, __this__eventProperties_copy_value);
      }
      this.eventProperties = __this__eventProperties;
    }
  }

  public DerivedEvent deepCopy() {
    return new DerivedEvent(this);
  }

  @Override
  public void clear() {
    setTimestampIsSet(false);
    this.timestamp = 0;
    this.componentId = null;
    this.eventName = null;
    this.eventProperties = null;
  }

  public long getTimestamp() {
    return this.timestamp;
  }

  public DerivedEvent setTimestamp(long timestamp) {
    this.timestamp = timestamp;
    setTimestampIsSet(true);
    return this;
  }

  public void unsetTimestamp() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TIMESTAMP_ISSET_ID);
  }

  /** Returns true if field timestamp is set (has been assigned a value) and false otherwise */
  public boolean isSetTimestamp() {
    return EncodingUtils.testBit(__isset_bitfield, __TIMESTAMP_ISSET_ID);
  }

  public void setTimestampIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TIMESTAMP_ISSET_ID, value);
  }

  public String getComponentId() {
    return this.componentId;
  }

  public DerivedEvent setComponentId(String componentId) {
    this.componentId = componentId;
    return this;
  }

  public void unsetComponentId() {
    this.componentId = null;
  }

  /** Returns true if field componentId is set (has been assigned a value) and false otherwise */
  public boolean isSetComponentId() {
    return this.componentId != null;
  }

  public void setComponentIdIsSet(boolean value) {
    if (!value) {
      this.componentId = null;
    }
  }

  public String getEventName() {
    return this.eventName;
  }

  public DerivedEvent setEventName(String eventName) {
    this.eventName = eventName;
    return this;
  }

  public void unsetEventName() {
    this.eventName = null;
  }

  /** Returns true if field eventName is set (has been assigned a value) and false otherwise */
  public boolean isSetEventName() {
    return this.eventName != null;
  }

  public void setEventNameIsSet(boolean value) {
    if (!value) {
      this.eventName = null;
    }
  }

  public int getEventPropertiesSize() {
    return (this.eventProperties == null) ? 0 : this.eventProperties.size();
  }

  public void putToEventProperties(String key, ComplexValue val) {
    if (this.eventProperties == null) {
      this.eventProperties = new HashMap<String,ComplexValue>();
    }
    this.eventProperties.put(key, val);
  }

  public Map<String,ComplexValue> getEventProperties() {
    return this.eventProperties;
  }

  public DerivedEvent setEventProperties(Map<String,ComplexValue> eventProperties) {
    this.eventProperties = eventProperties;
    return this;
  }

  public void unsetEventProperties() {
    this.eventProperties = null;
  }

  /** Returns true if field eventProperties is set (has been assigned a value) and false otherwise */
  public boolean isSetEventProperties() {
    return this.eventProperties != null;
  }

  public void setEventPropertiesIsSet(boolean value) {
    if (!value) {
      this.eventProperties = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TIMESTAMP:
      if (value == null) {
        unsetTimestamp();
      } else {
        setTimestamp((Long)value);
      }
      break;

    case COMPONENT_ID:
      if (value == null) {
        unsetComponentId();
      } else {
        setComponentId((String)value);
      }
      break;

    case EVENT_NAME:
      if (value == null) {
        unsetEventName();
      } else {
        setEventName((String)value);
      }
      break;

    case EVENT_PROPERTIES:
      if (value == null) {
        unsetEventProperties();
      } else {
        setEventProperties((Map<String,ComplexValue>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TIMESTAMP:
      return Long.valueOf(getTimestamp());

    case COMPONENT_ID:
      return getComponentId();

    case EVENT_NAME:
      return getEventName();

    case EVENT_PROPERTIES:
      return getEventProperties();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TIMESTAMP:
      return isSetTimestamp();
    case COMPONENT_ID:
      return isSetComponentId();
    case EVENT_NAME:
      return isSetEventName();
    case EVENT_PROPERTIES:
      return isSetEventProperties();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof DerivedEvent)
      return this.equals((DerivedEvent)that);
    return false;
  }

  public boolean equals(DerivedEvent that) {
    if (that == null)
      return false;

    boolean this_present_timestamp = true;
    boolean that_present_timestamp = true;
    if (this_present_timestamp || that_present_timestamp) {
      if (!(this_present_timestamp && that_present_timestamp))
        return false;
      if (this.timestamp != that.timestamp)
        return false;
    }

    boolean this_present_componentId = true && this.isSetComponentId();
    boolean that_present_componentId = true && that.isSetComponentId();
    if (this_present_componentId || that_present_componentId) {
      if (!(this_present_componentId && that_present_componentId))
        return false;
      if (!this.componentId.equals(that.componentId))
        return false;
    }

    boolean this_present_eventName = true && this.isSetEventName();
    boolean that_present_eventName = true && that.isSetEventName();
    if (this_present_eventName || that_present_eventName) {
      if (!(this_present_eventName && that_present_eventName))
        return false;
      if (!this.eventName.equals(that.eventName))
        return false;
    }

    boolean this_present_eventProperties = true && this.isSetEventProperties();
    boolean that_present_eventProperties = true && that.isSetEventProperties();
    if (this_present_eventProperties || that_present_eventProperties) {
      if (!(this_present_eventProperties && that_present_eventProperties))
        return false;
      if (!this.eventProperties.equals(that.eventProperties))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_timestamp = true;
    list.add(present_timestamp);
    if (present_timestamp)
      list.add(timestamp);

    boolean present_componentId = true && (isSetComponentId());
    list.add(present_componentId);
    if (present_componentId)
      list.add(componentId);

    boolean present_eventName = true && (isSetEventName());
    list.add(present_eventName);
    if (present_eventName)
      list.add(eventName);

    boolean present_eventProperties = true && (isSetEventProperties());
    list.add(present_eventProperties);
    if (present_eventProperties)
      list.add(eventProperties);

    return list.hashCode();
  }

  @Override
  public int compareTo(DerivedEvent other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetTimestamp()).compareTo(other.isSetTimestamp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTimestamp()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.timestamp, other.timestamp);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetComponentId()).compareTo(other.isSetComponentId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetComponentId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.componentId, other.componentId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEventName()).compareTo(other.isSetEventName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEventName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.eventName, other.eventName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEventProperties()).compareTo(other.isSetEventProperties());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEventProperties()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.eventProperties, other.eventProperties);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("DerivedEvent(");
    boolean first = true;

    sb.append("timestamp:");
    sb.append(this.timestamp);
    first = false;
    if (!first) sb.append(", ");
    sb.append("componentId:");
    if (this.componentId == null) {
      sb.append("null");
    } else {
      sb.append(this.componentId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("eventName:");
    if (this.eventName == null) {
      sb.append("null");
    } else {
      sb.append(this.eventName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("eventProperties:");
    if (this.eventProperties == null) {
      sb.append("null");
    } else {
      sb.append(this.eventProperties);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'timestamp' because it's a primitive and you chose the non-beans generator.
    if (componentId == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'componentId' was not present! Struct: " + toString());
    }
    if (eventName == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'eventName' was not present! Struct: " + toString());
    }
    if (eventProperties == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'eventProperties' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DerivedEventStandardSchemeFactory implements SchemeFactory {
    public DerivedEventStandardScheme getScheme() {
      return new DerivedEventStandardScheme();
    }
  }

  private static class DerivedEventStandardScheme extends StandardScheme<DerivedEvent> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, DerivedEvent struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TIMESTAMP
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.timestamp = iprot.readI64();
              struct.setTimestampIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // COMPONENT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.componentId = iprot.readString();
              struct.setComponentIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // EVENT_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.eventName = iprot.readString();
              struct.setEventNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // EVENT_PROPERTIES
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map18 = iprot.readMapBegin();
                struct.eventProperties = new HashMap<String,ComplexValue>(2*_map18.size);
                String _key19;
                ComplexValue _val20;
                for (int _i21 = 0; _i21 < _map18.size; ++_i21)
                {
                  _key19 = iprot.readString();
                  _val20 = new ComplexValue();
                  _val20.read(iprot);
                  struct.eventProperties.put(_key19, _val20);
                }
                iprot.readMapEnd();
              }
              struct.setEventPropertiesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetTimestamp()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'timestamp' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, DerivedEvent struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(TIMESTAMP_FIELD_DESC);
      oprot.writeI64(struct.timestamp);
      oprot.writeFieldEnd();
      if (struct.componentId != null) {
        oprot.writeFieldBegin(COMPONENT_ID_FIELD_DESC);
        oprot.writeString(struct.componentId);
        oprot.writeFieldEnd();
      }
      if (struct.eventName != null) {
        oprot.writeFieldBegin(EVENT_NAME_FIELD_DESC);
        oprot.writeString(struct.eventName);
        oprot.writeFieldEnd();
      }
      if (struct.eventProperties != null) {
        oprot.writeFieldBegin(EVENT_PROPERTIES_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRUCT, struct.eventProperties.size()));
          for (Map.Entry<String, ComplexValue> _iter22 : struct.eventProperties.entrySet())
          {
            oprot.writeString(_iter22.getKey());
            _iter22.getValue().write(oprot);
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DerivedEventTupleSchemeFactory implements SchemeFactory {
    public DerivedEventTupleScheme getScheme() {
      return new DerivedEventTupleScheme();
    }
  }

  private static class DerivedEventTupleScheme extends TupleScheme<DerivedEvent> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DerivedEvent struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI64(struct.timestamp);
      oprot.writeString(struct.componentId);
      oprot.writeString(struct.eventName);
      {
        oprot.writeI32(struct.eventProperties.size());
        for (Map.Entry<String, ComplexValue> _iter23 : struct.eventProperties.entrySet())
        {
          oprot.writeString(_iter23.getKey());
          _iter23.getValue().write(oprot);
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DerivedEvent struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.timestamp = iprot.readI64();
      struct.setTimestampIsSet(true);
      struct.componentId = iprot.readString();
      struct.setComponentIdIsSet(true);
      struct.eventName = iprot.readString();
      struct.setEventNameIsSet(true);
      {
        org.apache.thrift.protocol.TMap _map24 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.eventProperties = new HashMap<String,ComplexValue>(2*_map24.size);
        String _key25;
        ComplexValue _val26;
        for (int _i27 = 0; _i27 < _map24.size; ++_i27)
        {
          _key25 = iprot.readString();
          _val26 = new ComplexValue();
          _val26.read(iprot);
          struct.eventProperties.put(_key25, _val26);
        }
      }
      struct.setEventPropertiesIsSet(true);
    }
  }

}

