/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package eu.proasense.internal;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-3-31")
public class SimpleEvent implements org.apache.thrift.TBase<SimpleEvent, SimpleEvent._Fields>, java.io.Serializable, Cloneable, Comparable<SimpleEvent> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SimpleEvent");

  private static final org.apache.thrift.protocol.TField TIMESTAMP_FIELD_DESC = new org.apache.thrift.protocol.TField("timestamp", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField SENSOR_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("sensorId", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField EVENT_PROPERTIES_FIELD_DESC = new org.apache.thrift.protocol.TField("eventProperties", org.apache.thrift.protocol.TType.MAP, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SimpleEventStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SimpleEventTupleSchemeFactory());
  }

  public long timestamp; // required
  public String sensorId; // required
  public Map<String,ComplexValue> eventProperties; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TIMESTAMP((short)1, "timestamp"),
    SENSOR_ID((short)2, "sensorId"),
    EVENT_PROPERTIES((short)3, "eventProperties");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TIMESTAMP
          return TIMESTAMP;
        case 2: // SENSOR_ID
          return SENSOR_ID;
        case 3: // EVENT_PROPERTIES
          return EVENT_PROPERTIES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TIMESTAMP_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TIMESTAMP, new org.apache.thrift.meta_data.FieldMetaData("timestamp", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.SENSOR_ID, new org.apache.thrift.meta_data.FieldMetaData("sensorId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.EVENT_PROPERTIES, new org.apache.thrift.meta_data.FieldMetaData("eventProperties", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ComplexValue.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SimpleEvent.class, metaDataMap);
  }

  public SimpleEvent() {
  }

  public SimpleEvent(
    long timestamp,
    String sensorId,
    Map<String,ComplexValue> eventProperties)
  {
    this();
    this.timestamp = timestamp;
    setTimestampIsSet(true);
    this.sensorId = sensorId;
    this.eventProperties = eventProperties;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SimpleEvent(SimpleEvent other) {
    __isset_bitfield = other.__isset_bitfield;
    this.timestamp = other.timestamp;
    if (other.isSetSensorId()) {
      this.sensorId = other.sensorId;
    }
    if (other.isSetEventProperties()) {
      Map<String,ComplexValue> __this__eventProperties = new HashMap<String,ComplexValue>(other.eventProperties.size());
      for (Map.Entry<String, ComplexValue> other_element : other.eventProperties.entrySet()) {

        String other_element_key = other_element.getKey();
        ComplexValue other_element_value = other_element.getValue();

        String __this__eventProperties_copy_key = other_element_key;

        ComplexValue __this__eventProperties_copy_value = new ComplexValue(other_element_value);

        __this__eventProperties.put(__this__eventProperties_copy_key, __this__eventProperties_copy_value);
      }
      this.eventProperties = __this__eventProperties;
    }
  }

  public SimpleEvent deepCopy() {
    return new SimpleEvent(this);
  }

  @Override
  public void clear() {
    setTimestampIsSet(false);
    this.timestamp = 0;
    this.sensorId = null;
    this.eventProperties = null;
  }

  public long getTimestamp() {
    return this.timestamp;
  }

  public SimpleEvent setTimestamp(long timestamp) {
    this.timestamp = timestamp;
    setTimestampIsSet(true);
    return this;
  }

  public void unsetTimestamp() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TIMESTAMP_ISSET_ID);
  }

  /** Returns true if field timestamp is set (has been assigned a value) and false otherwise */
  public boolean isSetTimestamp() {
    return EncodingUtils.testBit(__isset_bitfield, __TIMESTAMP_ISSET_ID);
  }

  public void setTimestampIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TIMESTAMP_ISSET_ID, value);
  }

  public String getSensorId() {
    return this.sensorId;
  }

  public SimpleEvent setSensorId(String sensorId) {
    this.sensorId = sensorId;
    return this;
  }

  public void unsetSensorId() {
    this.sensorId = null;
  }

  /** Returns true if field sensorId is set (has been assigned a value) and false otherwise */
  public boolean isSetSensorId() {
    return this.sensorId != null;
  }

  public void setSensorIdIsSet(boolean value) {
    if (!value) {
      this.sensorId = null;
    }
  }

  public int getEventPropertiesSize() {
    return (this.eventProperties == null) ? 0 : this.eventProperties.size();
  }

  public void putToEventProperties(String key, ComplexValue val) {
    if (this.eventProperties == null) {
      this.eventProperties = new HashMap<String,ComplexValue>();
    }
    this.eventProperties.put(key, val);
  }

  public Map<String,ComplexValue> getEventProperties() {
    return this.eventProperties;
  }

  public SimpleEvent setEventProperties(Map<String,ComplexValue> eventProperties) {
    this.eventProperties = eventProperties;
    return this;
  }

  public void unsetEventProperties() {
    this.eventProperties = null;
  }

  /** Returns true if field eventProperties is set (has been assigned a value) and false otherwise */
  public boolean isSetEventProperties() {
    return this.eventProperties != null;
  }

  public void setEventPropertiesIsSet(boolean value) {
    if (!value) {
      this.eventProperties = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TIMESTAMP:
      if (value == null) {
        unsetTimestamp();
      } else {
        setTimestamp((Long)value);
      }
      break;

    case SENSOR_ID:
      if (value == null) {
        unsetSensorId();
      } else {
        setSensorId((String)value);
      }
      break;

    case EVENT_PROPERTIES:
      if (value == null) {
        unsetEventProperties();
      } else {
        setEventProperties((Map<String,ComplexValue>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TIMESTAMP:
      return Long.valueOf(getTimestamp());

    case SENSOR_ID:
      return getSensorId();

    case EVENT_PROPERTIES:
      return getEventProperties();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TIMESTAMP:
      return isSetTimestamp();
    case SENSOR_ID:
      return isSetSensorId();
    case EVENT_PROPERTIES:
      return isSetEventProperties();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SimpleEvent)
      return this.equals((SimpleEvent)that);
    return false;
  }

  public boolean equals(SimpleEvent that) {
    if (that == null)
      return false;

    boolean this_present_timestamp = true;
    boolean that_present_timestamp = true;
    if (this_present_timestamp || that_present_timestamp) {
      if (!(this_present_timestamp && that_present_timestamp))
        return false;
      if (this.timestamp != that.timestamp)
        return false;
    }

    boolean this_present_sensorId = true && this.isSetSensorId();
    boolean that_present_sensorId = true && that.isSetSensorId();
    if (this_present_sensorId || that_present_sensorId) {
      if (!(this_present_sensorId && that_present_sensorId))
        return false;
      if (!this.sensorId.equals(that.sensorId))
        return false;
    }

    boolean this_present_eventProperties = true && this.isSetEventProperties();
    boolean that_present_eventProperties = true && that.isSetEventProperties();
    if (this_present_eventProperties || that_present_eventProperties) {
      if (!(this_present_eventProperties && that_present_eventProperties))
        return false;
      if (!this.eventProperties.equals(that.eventProperties))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_timestamp = true;
    list.add(present_timestamp);
    if (present_timestamp)
      list.add(timestamp);

    boolean present_sensorId = true && (isSetSensorId());
    list.add(present_sensorId);
    if (present_sensorId)
      list.add(sensorId);

    boolean present_eventProperties = true && (isSetEventProperties());
    list.add(present_eventProperties);
    if (present_eventProperties)
      list.add(eventProperties);

    return list.hashCode();
  }

  @Override
  public int compareTo(SimpleEvent other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetTimestamp()).compareTo(other.isSetTimestamp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTimestamp()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.timestamp, other.timestamp);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSensorId()).compareTo(other.isSetSensorId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSensorId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sensorId, other.sensorId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEventProperties()).compareTo(other.isSetEventProperties());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEventProperties()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.eventProperties, other.eventProperties);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SimpleEvent(");
    boolean first = true;

    sb.append("timestamp:");
    sb.append(this.timestamp);
    first = false;
    if (!first) sb.append(", ");
    sb.append("sensorId:");
    if (this.sensorId == null) {
      sb.append("null");
    } else {
      sb.append(this.sensorId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("eventProperties:");
    if (this.eventProperties == null) {
      sb.append("null");
    } else {
      sb.append(this.eventProperties);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'timestamp' because it's a primitive and you chose the non-beans generator.
    if (sensorId == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'sensorId' was not present! Struct: " + toString());
    }
    if (eventProperties == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'eventProperties' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SimpleEventStandardSchemeFactory implements SchemeFactory {
    public SimpleEventStandardScheme getScheme() {
      return new SimpleEventStandardScheme();
    }
  }

  private static class SimpleEventStandardScheme extends StandardScheme<SimpleEvent> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SimpleEvent struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TIMESTAMP
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.timestamp = iprot.readI64();
              struct.setTimestampIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SENSOR_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.sensorId = iprot.readString();
              struct.setSensorIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // EVENT_PROPERTIES
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map8 = iprot.readMapBegin();
                struct.eventProperties = new HashMap<String,ComplexValue>(2*_map8.size);
                String _key9;
                ComplexValue _val10;
                for (int _i11 = 0; _i11 < _map8.size; ++_i11)
                {
                  _key9 = iprot.readString();
                  _val10 = new ComplexValue();
                  _val10.read(iprot);
                  struct.eventProperties.put(_key9, _val10);
                }
                iprot.readMapEnd();
              }
              struct.setEventPropertiesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetTimestamp()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'timestamp' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SimpleEvent struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(TIMESTAMP_FIELD_DESC);
      oprot.writeI64(struct.timestamp);
      oprot.writeFieldEnd();
      if (struct.sensorId != null) {
        oprot.writeFieldBegin(SENSOR_ID_FIELD_DESC);
        oprot.writeString(struct.sensorId);
        oprot.writeFieldEnd();
      }
      if (struct.eventProperties != null) {
        oprot.writeFieldBegin(EVENT_PROPERTIES_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRUCT, struct.eventProperties.size()));
          for (Map.Entry<String, ComplexValue> _iter12 : struct.eventProperties.entrySet())
          {
            oprot.writeString(_iter12.getKey());
            _iter12.getValue().write(oprot);
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SimpleEventTupleSchemeFactory implements SchemeFactory {
    public SimpleEventTupleScheme getScheme() {
      return new SimpleEventTupleScheme();
    }
  }

  private static class SimpleEventTupleScheme extends TupleScheme<SimpleEvent> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SimpleEvent struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI64(struct.timestamp);
      oprot.writeString(struct.sensorId);
      {
        oprot.writeI32(struct.eventProperties.size());
        for (Map.Entry<String, ComplexValue> _iter13 : struct.eventProperties.entrySet())
        {
          oprot.writeString(_iter13.getKey());
          _iter13.getValue().write(oprot);
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SimpleEvent struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.timestamp = iprot.readI64();
      struct.setTimestampIsSet(true);
      struct.sensorId = iprot.readString();
      struct.setSensorIdIsSet(true);
      {
        org.apache.thrift.protocol.TMap _map14 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.eventProperties = new HashMap<String,ComplexValue>(2*_map14.size);
        String _key15;
        ComplexValue _val16;
        for (int _i17 = 0; _i17 < _map14.size; ++_i17)
        {
          _key15 = iprot.readString();
          _val16 = new ComplexValue();
          _val16.read(iprot);
          struct.eventProperties.put(_key15, _val16);
        }
      }
      struct.setEventPropertiesIsSet(true);
    }
  }

}

