FROM tomcat:8.0

EXPOSE 8080

ADD /home/proasense/proasense-storage/storage-reader/target/storage-reader.war /usr/local/tomcat/webapps/storage-reader.war
ADD /home/proasense/proasense-storage/storage-registry/target/storage-registry.war /usr/local/tomcat/webapps/storage-registry.war
